"""config – centralised paths, settings, and constants."""

from .paths import Paths
from .settings import Settings
from .constants import (
    SFREQ, BANDPASS, NOTCH_FREQS, EPOCH_TMIN, EPOCH_TMAX, BASELINE,
    REJECT_THRESHOLD, ICA_N_COMPONENTS, STIM_ONSET, STIM_CODES,
    REST_START, REST_END, REST_WINDOW, FREQ_BANDS, BANDS_FOR_FEATURES,
    ROI_MAP, SEGMENTS, WELCH_N_FFT, WELCH_N_OVERLAP, EPS,
    EARLOBE_CHANNELS, EOG_CHANNELS, EXG_ALL, BEHAV_COLUMNS,
)

__all__ = [
    "Paths", "Settings",
    "SFREQ", "BANDPASS", "NOTCH_FREQS", "EPOCH_TMIN", "EPOCH_TMAX",
    "BASELINE", "REJECT_THRESHOLD", "ICA_N_COMPONENTS",
    "STIM_ONSET", "STIM_CODES", "REST_START", "REST_END", "REST_WINDOW",
    "FREQ_BANDS", "BANDS_FOR_FEATURES", "ROI_MAP", "SEGMENTS",
    "WELCH_N_FFT", "WELCH_N_OVERLAP", "EPS",
    "EARLOBE_CHANNELS", "EOG_CHANNELS", "EXG_ALL", "BEHAV_COLUMNS",
]
